<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Tests\Fixtures\User;

/**
 * Factory for generating test User model instances.
 *
 * Creates fake user data for testing feature flag scoping and feature group membership
 * scenarios. The factory generates users with unique IDs, names, and email
 * addresses suitable for testing feature flag behavior across different contexts.
 *
 * @extends Factory<User>
 *
 * @author Brian Faust <brian@cline.sh>
 */
final class UserFactory extends Factory
{
    /**
     * The name of the model this factory creates.
     *
     * @var class-string<User>
     */
    protected $model = User::class;

    /**
     * Define the model's default state for testing.
     *
     * Generates a user with realistic name and unique email address.
     * The ID is automatically generated by Laravel/HasTogglPrimaryKey trait
     * based on the configured primary key type (id/uuid/ulid).
     *
     * @return array<string, mixed> Attribute values for the User model
     */
    public function definition(): array
    {
        return [
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
        ];
    }
}
